name: Deploy Streamlit to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user

            if [ -d Bad-Default-Prediction ]; then
              cd Bad-Default-Prediction
              git reset --hard
              git pull
            else
              git clone https://github.com/${{ github.reposito
